### ISSUE TITLE
Potential 1440p Recording Issues

### ISSUE THREAD

**Issue by Re1oads** [chpoit/utsushis-charm#33] opened 2022-07-06 03:27 UTC
**Device**
- PC 
  - For PC, what is your screen resolution: 1440p
  - For PC, what is your OS: Windows 11
- Game language: English
- App version: MH:Sunbreak -- 10.0.2.0 | utsushis-charm -- 1.6.2

** Problem(s) **
Please describe the issue in as much detail.

Reloads from reddit here, just following up from over there. 

Not sure whether it's due to recording in 1440p (heading to bed soon so don't have time to try 1080p tonight), but no text file information is being generated. The frames that are being extracted have the decoration portion of the image slightly cut off at the bottom. 

If it is related to your clips you can upload them by dragging them to the text box. If they are too big feel free to create a google drive link

First time using Google Drive, so I hope this link works: 

https://drive.google.com/file/d/1q3odt8HpHr6XEYIUtMW5OlzXLovB8DKh/view?usp=sharing 

You can also upload specific frames or pictures by dragging them too.

Here are a few frames that were generated. 

![frame0](https://user-images.githubusercontent.com/108778204/177461758-e09f3c35-f78e-4276-a67b-5dcaa1bef479.png)
![frame65](https://user-images.githubusercontent.com/108778204/177461760-94b05acf-efe6-4303-a700-6b58a63fac46.png)
![frame83](https://user-images.githubusercontent.com/108778204/177461762-ef25395d-9989-4b7c-b81a-3c2cd28359a5.png)
![frame96](https://user-images.githubusercontent.com/108778204/177461764-9fa94658-3000-429a-a093-d2a49774a9ab.png)

**Comment by chpoit** [comment] 2022-07-06 03:37
Thanks for this, I asked for file access. When you create google drive links you can usually set it so that "Anyone with the link can view“, it's usually just besides the area where you can copy the link.

Looking at the frames it's obvious to me that the game moves the GUI elements ever so slightly on higher resolutions so I will have to manage it and create new filters, thanks in advance for the clips, now I'll just have to hope someone playing in 4k has this issue and is willing to share with me.

It could always be the scaler, but it shouldnt just delete image data in a way that significantly moves the contents.

**Comment by Re1oads** [comment] 2022-07-06 03:42
Gave you access (I hope).

**Comment by ScarlettoZYX** [comment] 2022-07-06 05:40
I'm having a similar issue with the Switch. I've captured the video on my PC with my Elgato @ 1080p/60fps. I've linked the video below and included some frames the program generated.

https://1drv.ms/v/s!AiAZZHeMdIghheBXPohRFiVkYDxCcw?e=VjEzjL

![frame102](https://user-images.githubusercontent.com/75466880/177476725-c87e16bf-ad4b-455f-99ba-a2d3526394df.png)
![frame94](https://user-images.githubusercontent.com/75466880/177476734-5fe61872-cb9a-47d9-8db1-37a0a20d9723.png)
![frame85](https://user-images.githubusercontent.com/75466880/177476744-cd311e41-4d7f-4637-8664-83e42c36fd8f.png)

**Comment by chpoit** [comment] 2022-07-06 10:39
> Gave you access (I hope).

Yes, thank you, I just noticed you apppear to play in windowed mode, could you try to play in full screen or borderless windowed when you record?

**Comment by Re1oads** [comment] 2022-07-06 11:52
> > Gave you access (I hope).
> 
> Yes, thank you, I just noticed you apppear to play in windowed mode, could you try to play in full screen or borderless windowed when you record?

I was thinking that could have had something to do with it too. I'll give it a try when I get home from work later today. Only reason I was in windowed mode was because I could only get shadowplay to record one of my monitors so I set sunbreak to windowed to quickly switch screens.

**Comment by chpoit** [comment] 2022-07-06 12:14
> > > Gave you access (I hope).
> > 
> > 
> > Yes, thank you, I just noticed you apppear to play in windowed mode, could you try to play in full screen or borderless windowed when you record?
> 
> I was thinking that could have had something to do with it too. I'll give it a try when I get home from work later today. Only reason I was in windowed mode was because I could only get shadowplay to record one of my monitors so I set sunbreak to windowed to quickly switch screens.

You could alway try using OBS to record instead, just set a new "Game capture" and it *should* work without you even needing to run OBS in admin mode, unless you run MHR in admin mode, in which case you will need to run obs as admin, which might also be your shadowplay issue.

If it does turn out that this was caused by windowed mode I'll try adding "windowed mode" and "black bar" dectection to fix both you and ScarlettoZYX's issue

**Comment by Re1oads** [comment] 2022-07-06 22:39
Hey, looks like windowed mode may have been the issue. I just made another recording using borderless windowed; at 1440p, and the frames and .txt files generated correctly.

**Comment by chpoit** [comment] 2022-07-06 22:42
> Hey, looks like windowed mode may have been the issue. I just made another recording using borderless windowed; at 1440p, and the frames and .txt files generated correctly.

Tthanks a lot for letting me know, I'm glad I don't have to do any more pixel tweaking for each resolution :)

**Comment by ScarlettoZYX** [comment] 2022-07-07 01:44
So it turns out my Switch had the screen size set to 96% which was causing the incorrect borders. I set it back to 100% and rerecorded the charms and Utsushi correctly captured them.

**Comment by chpoit** [comment] 2022-07-07 02:18
I will close this issue since it was mostly recording based

**Closed by chpoit** 2022-07-07 02:18 UTC
Labels: other
